### ISSUE TITLE
A problem when bold Chinese with markdown

### ISSUE THREAD

**Issue by letiantian** [SublimeText/Spacegray#106]
when I use spacegray as the theme of st3，I find a problem  when bold Chinese with markdown. Maybe it's a bug~

I type`**aabc你好，世界**` in st3. In spacegray, It looks like as follows:
![00](https://cloud.githubusercontent.com/assets/4159935/2992826/8514d0a0-dc9c-11e3-810e-35c67fff5710.png)

In the right circumstances, it should have looked like as follows:
![01](https://cloud.githubusercontent.com/assets/4159935/2992842/d4e126ba-dc9c-11e3-90c1-d2fa844721a4.png)

**Comment by deathaxe** [comment]
That was a font rendering bug of ST.
