### ISSUE TITLE
Opening bracket in HTML difficult to see

### ISSUE THREAD

**Issue by claviska** [SublimeText/Spacegray#111]
To reproduce:
1. Create a new file
2. Set syntax to HTML
3. Type: `<`

The result is this:

![vjd-xmvlvg8ids-gufss_v_b66pqkwkzcz7uyyuwqbw](https://cloud.githubusercontent.com/assets/55639/3176491/e1237428-ec05-11e3-80e7-6f0aa0d495fc.png)

Edit: it only occurs when you have `highlight_line` enabled and the current line is selected.

**Comment by deathaxe** [comment]
Can't reproduce anymore. If `highlight_line` was involved it may have been a ST rendering bug.
