### ISSUE TITLE
Change color text in sidebar and tab (out and hover)

### ISSUE THREAD

**Issue by gregoirenoyelle** [SublimeText/Spacegray#115]
Hi
Thanks for your theme. Love it!
Could you tell me how to change color text in sidebar and tab for out and hover. 
That's too dark for me and I want to make it well.
I use "theme": "Spacegray.sublime-theme"
Thanks

**Comment by vdzundza** [comment]
+1

**Comment by deathaxe** [comment]
Would require to modify `"class": "sidebar_label"` rules.
