### ISSUE TITLE
Windows (7, 8.1) tabs labels with large, xlarge font-sizes

### ISSUE THREAD

**Issue by amscript** [SublimeText/Spacegray#116]
Sublime Text 2.0.2, tested in Windows 7 and Windows 8.1.
here's screenshot:
![spacegray_tabs](https://cloud.githubusercontent.com/assets/5437930/3537842/9b4e5ee4-0826-11e4-85ff-3d7f2053ceed.png)

**Comment by jardicc** [comment]
I have same problem ST3 win7

**Comment by MoradHamdy** [comment]
Did anyone found a solution?

**Comment by jardicc** [comment]
When i set smaller text in tab then it's ok. 
In the end I used this theme: https://packagecontrol.io/packages/Theme%20-%20Afterglow which is similar but with a good documentantation and filetype-icons

**Comment by ihorvorotnov** [comment]
I can confirm the same bug on ST3 Build 3083 and Windows 10.

**Comment by rushmash** [comment]
Hey, I also confirm the same bug on st3 3083, win7
![image](https://cloud.githubusercontent.com/assets/2829092/10713330/ffe06392-7ab8-11e5-93e8-a27b79d39e5e.png)

**Comment by 70data** [comment]
set like this can make it ok

    "spacegray_tabs_font_normal": true,
    "spacegray_tabs_xlarge": true,
    "enable_tab_scrolling": false
