### ISSUE TITLE
Increase contrast in Spacegray Light theme

### ISSUE THREAD

**Issue by hmistry** [SublimeText/Spacegray#127]
Really like the Spacegray dark theme but like all dark themes, its useless in sunlight. I'm trying to use the Light theme but its still kind of hard to read because some of the text colors are on the lighter side and thus the contrast is low. I think it would help a lot if the text colors was made just a notch darker to increase the contrast so the theme is usable in bright daylight.

The text colors of particular concern (using ruby lang) are:
- the sidebar files/folders
- comments
- the light green syntax color for strings
- the magenta/purple for if's, def, methods statements
- the orange for class names

**Comment by deathaxe** [comment]
Both theme and color schemes have been adjused to prvode more contrast.
