### ISSUE TITLE
Italics on the tab bar

### ISSUE THREAD

**Issue by benjojo** [SublimeText/Spacegray#130]
Is this indented? I can't see this in the screenshots on the repo.

![](http://i.imgur.com/eC2kF6W.png)

**Comment by WilsonMontelo** [comment]
How do you put the normal font in windows? I do not want the tabs in Italic

**Comment by peterkos** [comment]
@WilsonMontelo Go into the `Spacegray.sublime-theme` file (or the corresponding .sublime-theme for whatever variant you're using), and change the line 
````
"font.italic": true
````
to
````
"font.italic": false
````
underneath the `// TAB LABELS` section. 

[Here's where it's located](https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L171) in the main Spacegray.sublime-theme file.

**Comment by WilsonMontelo** [comment]
@peterkos  It does not work, this is the code I used
![italiv](https://cloud.githubusercontent.com/assets/12366938/23837221/a6f5d68e-0763-11e7-8ff9-9efd9c27a583.png)

**Comment by peterkos** [comment]
Have you tried changing the actual `.sublime-theme` file itself, not your Preferences?

**Comment by WilsonMontelo** [comment]
does not work =/
![sem-titulo-1](https://cloud.githubusercontent.com/assets/12366938/23837711/3ec3ffd4-076b-11e7-9fab-0195c92ccb03.png)

**Comment by peterkos** [comment]
@WilsonMontelo Try setting `tabs_label_not_italic` to `true`?
