### ISSUE TITLE
Find controls colours

### ISSUE THREAD

**Issue by samizzo** [SublimeText/Spacegray#140]
On the main page screenshot the find controls are a different colour to the background:

![](http://kkga.github.io/spacegray/assets/spacegray.png)

but when I install the theme the colours look like the screenshot on the github page:

![](https://github.com/kkga/spacegray/raw/master/Screenshots/spacegray.png)

In the second screenshot the find buttons and text input field aren't as clearly visible because the background colour is the same as the control colour. Can I get it to look like the first screenshot, or is that out of date?

**Comment by samizzo** [comment]
Any comment on the difference in the screenshots?

**Comment by deathaxe** [comment]
I can't say anything about the origin of 1st screenshot and actually haven't realized that landing page at all before. Input control and buttons look rather like ST's default theme.

2nd screenshot has been pushed 2013 and still matches the the theme.

Its find panel's design fullfills the attribute of a "hyperminimal theme" better than 1st one and such is not subject of any planned change.
