### ISSUE TITLE
Sidebar tree and tab height messed up on Windows

### ISSUE THREAD

**Issue by Francisc** [SublimeText/Spacegray#141]
Hello,

Is there any way to fix the misalignment between height of sidebar tree items and tab height?
I can't use it as it is now, it's the only thing I see... ha.

![ss](https://cloud.githubusercontent.com/assets/699657/5420050/0263091a-825a-11e4-8242-b6c066ecd756.jpg)

**Comment by deathaxe** [comment]
No. sidebar_control and layout_control form a 2-column layout. The latter containing edit_controls consisting of tabset_control and views.

Whatever you try, as soon as sidebar is scrolled by some amount, selections might look off as displayed in screenshot.
