### ISSUE TITLE
I think this color scheme is much better

### ISSUE THREAD

**Issue by KirillArtemenko** [SublimeText/Spacegray#143]
I love a SPACEGRAY theme, but color scheme is need to be more bright.
Look this: https://github.com/itsthatguy/theme-itg-flat/blob/master/itg.dark.tmTheme
I think this colors is perfect for Spacegray. Thx!

**Comment by theblacklion** [comment]
Have you tried the eighties variant? I would be really sad if the colors would be changed - very happy with the current state there.

**Comment by KirillArtemenko** [comment]
I only suggested adding another option color scheme in the package, no need to remove the old sets.
This set looks great: https://yadi.sk/i/XfGn8at8dqBXX

**Comment by deathaxe** [comment]
Ugly!

**Comment by KirillArtemenko** [comment]
> Ugly!

Bro, that was 9 years ago. Of course, it doesn't look so nice and modern now.
