### ISSUE TITLE
Some of the icons are not applied on ST3

### ISSUE THREAD

**Issue by tnraro** [SublimeText/Spacegray#144]
![2015-01-29 05 39 26](https://cloud.githubusercontent.com/assets/8617317/5946462/3a42423a-a779-11e4-964d-88a3beb6987f.png)

Like this.

**Comment by bdefore** [comment]
i had issues with icons not displaying correctly because I'd manually installed (not via package manager) and had put the theme in Packages/User rather than Packages. Once I moved it there and restarted, the icons showed up. It does seem contrary to ST3 folder structure to have it that way though.

**Comment by nornie** [comment]
I don't know how to do anything like that

**Comment by bdefore** [comment]
@nornie Assuming you have Homebrew installed, you can run the following from Terminal:
```
brew install wget && wget https://github.com/kkga/spacegray/archive/master.zip && unzip master.zip && mv spacegray-master "$SUBLIME_SUPPORT"/Packages/Theme\ -\ Spacegray
```
And then from within Sublime hit CMD-, (command-comma) to open your user preferences. You'll want to add the following two lines at the end:
```
  "theme": "Spacegray.sublime-theme",
  "color_scheme": "Packages/Theme - Spacegray/base16-ocean.dark.tmTheme"
```
It's possible nothing will be in there, so your final settings will look like this:
```
{
  "theme": "Spacegray.sublime-theme",
  "color_scheme": "Packages/Theme - Spacegray/base16-ocean.dark.tmTheme"
}
```
