### ISSUE TITLE
Question About Keyword Highlighting

### ISSUE THREAD

**Issue by Jaballadares** [SublimeText/Spacegray#148]
Forgive me if this is the wrong place to post a question, I'm new to the entire github community. 

I was curious if Spacegray supported "keyword highlighting"? I messed around with webstorm and appreciated how it gave me even more context by highlighting keywords. I've attached a screenshot of both editors.

Sorry if this has been answered already in the past!

Spacegray in Sublime:
![sublime-spacegray](https://cloud.githubusercontent.com/assets/4951251/6223252/97dd5dcc-b619-11e4-9f82-54031d247fa3.png)

Spacegray in Webstorm:
![webstorm-spacegray](https://cloud.githubusercontent.com/assets/4951251/6223253/998b9378-b619-11e4-89e2-f07fadddea7c.png)

**Comment by deathaxe** [comment]
Highlighting therefore is a 2-step-process:

1. syntax definitions are used to assign `scopes` to tokens (e.g.: keywords)
2. color schemes provide rules to tint `scopes`.

This package only provides color schemes.

They can be customized to some extend, to tweak highlighting.
