### ISSUE TITLE
Support for BracketHighligther

### ISSUE THREAD

**Issue by diego898** [SublimeText/Spacegray#175]
Is it possible to add support for this plugin to the theme?

https://facelessuser.github.io/BracketHighlighter/

**Comment by deathaxe** [comment]
BracketHighlighter uses pre-defined color scopes such as `region.redish`, which are defined by variables `--redish`. Those are defined using base16 color palette as of https://github.com/SublimeText/Spacegray/commit/e3aafa16363ac4b094471e0d9591b6964a1955af.
