### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by buildersbrewery** [SublimeText/Spacegray#183]
https://www.sublimetext.com/3dev

> Build 3116
> - Color Schemes: Added popupCss key, for defining default popup style sheets.

**Comment by buildersbrewery** [comment]
Docs:

* https://www.sublimetext.com/docs/3/color_schemes.html#global_settings-css
* https://www.sublimetext.com/docs/3/minihtml.html
* https://www.sublimetext.com/docs/3/minihtml.html#css

**Comment by deathaxe** [comment]
ST4 derives default popup styles from color schemes. Custom popupCss may even break things.
