### ISSUE TITLE
No icon (on sidebar) for Pug files (formerly called Jade)

### ISSUE THREAD

**Issue by MeetThePatel** [SublimeText/Spacegray#184]

**Comment by nightwind93** [comment]
Yes,Hope that they can add the feature

**Comment by kkga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consider making Grid prototype more flexible](https://trello.com/c/qPqoaEnc/22-consider-making-grid-prototype-more-flexible)
