### ISSUE TITLE
Open files close icon margin issue after setting 'spacegray_fileicons:true'

### ISSUE THREAD

**Issue by Halomaple** [SublimeText/Spacegray#188]
After setting 'spacegray_fileicons:true', the open files close icon is not totally shown, only part of it.  Resizing window doesn't work. 

<img width="334" alt="spacegray-open-file-icon-issue" src="https://cloud.githubusercontent.com/assets/7535597/20692363/5e63597a-b612-11e6-8fd1-91eddb557e6a.png">

**Comment by marcofugaro** [comment]
Yeah unfortunately you can control the offset only of the whole tree, so that means moving also the project FOLDERS

Here is the relative line if you want to play with it
https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L741

Any recommendation is welcome

**Comment by morschesholz** [comment]
I don't have a problem with the project folder being more indented.
I find it more important to see the status of the opened files (e.g. yellow circle for unsaved ones etc.).

**Comment by zhuziyi1989** [comment]
"indent_offset": 10

**Comment by nean-and-i** [comment]
should be by default `"indent_offset": 10 ` as it is a quite annoying issue

**Comment by tobiasger** [comment]
@zhuziyi1989 How do I enter this in the settings file? Simply putting `"indent_offset": 10` doesn't seem to work.

**Comment by tobiasger** [comment]
I also realised that if you've installed [https://github.com/ihodev/a-file-icon](A File Icon) you can put `"force_mode": true` in the settings for A File Icon to overwrite the theme icons, and they seem to work perfectly without the indent issue.

**Comment by Halomaple** [comment]
@tobiasger  you need to edit Spacegray.sublime-theme and set `"indent_offset": 1`. But I think the way you mentioned is a good alternative for now. Thanks.
