### ISSUE TITLE
Sidebar tree scroll bar only resizing horizontally

### ISSUE THREAD

**Issue by michaelegan** [SublimeText/Spacegray#192]
Hello - seems like the tree scroll bar is only resizing the sidebar panel. Scrolling in the tree is only available by mouse wheel which is slower on larger trees.

<img width="548" alt="screen shot 2016-11-29 at 10 11 12 am" src="https://cloud.githubusercontent.com/assets/628916/20713167/9901db00-b61d-11e6-8f8d-c88a499d3ae1.png">

**Comment by marcofugaro** [comment]
I think the sidebar scrollbar is not grabbable, have you tried with other themes? I think it's a Sublime Text issue, not related to spacegray

**Comment by michaelegan** [comment]
Hmm, the default theme and previous Spacegray builds have a grabbable bar here. It seems like it's not an app-wide issue.

<img width="439" alt="screen shot 2016-11-29 at 1 50 02 pm" src="https://cloud.githubusercontent.com/assets/628916/20721849/c74b70b2-b63a-11e6-8689-ada5dcff1797.png">

**Comment by EdBrereton** [comment]
I just tried it on my install and it is grabbable. The range to grab it is very small though - it seems to be about a pixel or two between resizing the panels and selecting a file. I'm not sure how this would scale with dpi, so it may be that on better monitors it is effectively ungrabbable...

**Comment by michaelegan** [comment]
Okay, thanks for checking into it. I'm on the latest MacOS here if that helps. I love using this theme I'll have to switch to another for workflow reasons until a more easily grabbable bar returns on retina screens. Keep up the great work!

**Comment by marcofugaro** [comment]
Alright, the scrollbar is wide 2px, which is taken from [here](https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L314) for vertical and [here](https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L324) for horizontal, best that can be done is to make it wider, but I don't know how it would fit with the theme.

**Comment by deathaxe** [comment]
Scrollbars are wider in current releases.
