### ISSUE TITLE
Turning icons off?

### ISSUE THREAD

**Issue by christoffwalker** [SublimeText/Spacegray#193]
Hey, 

Trying to turn the new icons off - Sorry, no offence!

But adding this to user settings has no effect:
"spacegray_fileicons": false,

Am I missing something else?

Many thanks
Chris

**Comment by marcofugaro** [comment]
Just tried it now and it turns my icons off just fine,

what is your sublime version?

**Comment by christoffwalker** [comment]
Hey Marco, 

Latest build - 3126.

I also just tried my laptop as well, still no luck. 

Have tried restarting but no change.

**Comment by marcofugaro** [comment]
Could you please share your `Preferences.sublime-settings`?

**Comment by christoffwalker** [comment]
{
	"always_show_minimap_viewport": true,
	"auto_close_tags": true,
	"auto_find_in_selection": true,
	"bold_folder_labels": false,
	"caret_extra_bottom": 1,
	"caret_style": "phase",
	"close_windows_when_empty": true,
	"color_scheme": "Packages/Theme - Spacegray/base16-ocean.dark.tmTheme",
	"copy_with_empty_selection": true,
	"dictionary": "Packages/Language - English/en_GB.dic",
	"drag_text": false,
	"draw_minimap_border": true,
	"ensure_newline_at_eof_on_save": true,
	"folder_exclude_patterns":
	[
		"_notes"
	],
	"font_face": "consolas",
	"font_options":
	[
		"subpixel_antialias"
	],
	"font_size": 10,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"hot_exit": true,
	"ignored_packages":
	[
		"Browser Refresh",
		"Vintage"
	],
	"minimap_scroll_to_clicked_text": false,
	"overlay_scroll_bars": "enabled",
	"preview_on_click": true,
	"remember_open_files": false,
	"scroll_past_end": false,
	"scroll_speed": 0,
	"shift_tab_unindent": true,
	"show_full_path": false,
	"spacegray_fileicons": false,
	"spell_check": false,
	"theme": "Spacegray.sublime-theme",
	"word_wrap": true
}

**Comment by vitoravelino** [comment]
Hey there!

Despite the fact of not turning it off as mentioned above, it doesn't show properly the icons either for me. Check out the screenshot below.

<img width="173" alt="screenshot 2016-12-01 13 00 59" src="https://cloud.githubusercontent.com/assets/188554/20798524/3ebe290a-b7c6-11e6-81d3-5614308ca97c.png">

By the way, looking forward for the icons. Thanks! :D

Version: 3126

**Comment by nicooprat** [comment]
I'm facing the exact same problem. Also the "unsaved changes" icon in tab bar has the same ~orange weird icon. The `spacegray_fileicons` setting has no effect.

**Comment by marcofugaro** [comment]
Sorry guys, can't replicate the issue, let's go one step above, what is your OS?
Also any help with the debug is welcome.

**Comment by christoffwalker** [comment]
I'm on Windows 10.

I'll try and re-install it over the weekend, with just ST and Spacegrey, and report back.

**Comment by nicooprat** [comment]
Mac OS latest, and Sublime Text 3 latest. Don't have time to try to reinstall for now though...

**Comment by vitoravelino** [comment]
I realized that the path of icons in the .sublime-theme file was referring to `Theme - Spacegray` and not `Spacegray`. I have no idea why the rename happened. After changing it, the default old icons (arrows) worked like a charm. 

I'll try to reinstall because the files doesn't reflect the master.

**Comment by nicooprat** [comment]
I can confirm that resetting this file worked for me: https://github.com/kkga/spacegray/blob/master/Spacegray%20Oceanic.sublime-theme

**Comment by deathaxe** [comment]
If multiple packages define file type icons via `file_type_...tmPreference` with different names for same scopes, ST picks up the first definition one it finds. Icon textures however must reside next to or in _icons_ folder next to a sublime-theme file.

Hence, if another package defines different file types, which Spacegray does not provide icon textures for, no icon is visible. see: https://github.com/sublimehq/sublime_text/issues/2520.

**Comment by deathaxe** [comment]
If A File Icon is installed, it may prevent file_type icons from being hidden if `spacegray_fileicons: false` is set.
