### ISSUE TITLE
Dialogs aren't correctly styled

### ISSUE THREAD

**Issue by appsforartists** [SublimeText/Spacegray#210]
<img width="512" alt="screen shot 2018-03-29 at 9 01 26 am" src="https://user-images.githubusercontent.com/926648/38100927-a19155d6-3333-11e8-920f-fa6dd1123500.png">

See https://github.com/SublimeTextIssues/Core/issues/2246#event-1548284252

Possibly a dupe of #183.

**Comment by buildersbrewery** [comment]
Docs: https://www.sublimetext.com/docs/3/themes.html#elements-dialogs

---

@appsforartists This issue is unrelated to #183
