### ISSUE TITLE
Git + sidebar + gutter

### ISSUE THREAD

**Issue by alecmev** [SublimeText/Spacegray#214]
Sublime Text now has a simple Git integration. Problem is, the dots it displays in the sidebar are distracting for those who are used to depending on the gutter indicators (e.g. from GitGutter or SublimeLinter). This is being discussed in [this forum post](https://forum.sublimetext.com/t/git-file-status-badges/40694).

Currently there's no alternative display mode, so the only fix, besides outright disabling the integration, is theming. Thankfully, as mentioned in that post, the necessary adjustments have already been made in another theme - [Toxin](https://github.com/p3lim/sublime-toxin) - so this would be relatively easy to replicate in Spacegray.

However, would such a change be welcome? @marcofugaro @kkga

**Comment by jeremejevs** [comment]
@marcofugaro Not in the immediate future, I'm afraid, so this is up for grabs!

**Comment by jeremejevs** [comment]
@marcofugaro https://github.com/kkga/spacegray/pull/217
