### ISSUE TITLE
Emacs Set

### ISSUE THREAD

**Issue by arjunkathuria** [SublimeText/Spacegray#220]
lovely set of themes, love them on my sublime text, esp the spacegray eighties.

i know you're probably busy but can we expect an emacs version / port of these ?

Thanks for your work.

**Comment by kkga** [comment]
thanks!
I'm sure you can find an existing port of the base16-eighties colorscheme to emacs, e.g. https://github.com/belak/base16-emacs

**Comment by arjunkathuria** [comment]
i did actually. it's **really** not the same. The sublime one looks SO MUCH BETTER.

i was hoping to see, if there'd be an official port? since that saves me from having to maintain one.

but if not, i'll probably do it myself, take a day and match each thing in the eighties theme as close as i can, ITS JUST THAT GOOD.
