### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by alecmev** [SublimeText/Spacegray#221]
Was [planning to be one](https://github.com/SublimeText/Spacegray/pull/217#issuecomment-1211926915), but didn't have time, and ultimately switched to VS Code some months ago. There's evidence of people still caring about Spacegray (https://github.com/SublimeText/Spacegray/pull/217#issuecomment-1929779850, [package](https://packagecontrol.io/packages/Theme%20-%20Spacegray)), so would be lovely to have somebody look after it.

@FichteFoll @deathaxe Any "in the meanwhile" suggestions? I could merge that PR as-is and see how it goes, as it's opt-in.

**Comment by FichteFoll** [comment]
I've enabled notifications for the repo and also took a small glance at #217. I don't really deal with themes, but it should be enough to review PRs to a reasonable level (i.e. not rewriting everything), merge them and create new tags.

Unless we can find another dedicated maintainer, that's going to be the way forward, as far as packages in maintenance mode in the ST group are concerned.

**Comment by alecmev** [comment]
Thank you! The best "suggestion" I could get 😄

**Comment by cherradiyacyn** [comment]
This theme is awesome. Thank you ! It's better than [Gruvbox](https://github.com/Briles/gruvbox) on ST4.
The maintainers must work on the most important aspect that makes any theme a beast; it is `Customization`.
If you can guide me on how to add Customization, I want to contribute.

**Comment by alecmev** [comment]
@deathaxe Thank you 🙏
