### ISSUE TITLE
Font styling broke in latest update

### ISSUE THREAD

**Issue by appsforartists** [SublimeText/Spacegray#225]
Today, my font size and padding unexpectedly:

<img width="854" alt="Screenshot 2024-09-04 at 5 59 44 PM" src="https://github.com/user-attachments/assets/afb45442-c035-4e38-91e7-6afe9a39fc08">

I also notice that [an update was pushed yesterday](https://packagecontrol.io/packages/Theme%20-%20Spacegray).  I suspect the upgrade may have broken the styling.

**Comment by appsforartists** [comment]
Looks like there were many changes last night.  I followed the steps in the README, and adding this to the `UI: Customize Theme` fixes it:

```js
// Documentation at https://www.sublimetext.com/docs/themes.html
{
  "variables":
  {
    "font_face": "Lucida Grande",
    "font_size": 12,
  },
  "rules":
  [
  ]
}
```

**Comment by FichteFoll** [comment]
Which ST build are you using?

**Comment by appsforartists** [comment]
> Which ST build are you using?

`4180`

**Comment by FichteFoll** [comment]
Hm, this issue is odd because the theme uses `"system"` by default, which is the same as the Default and Adaptive themes use.

You wouldn't happen do have some override of the theme lying around? What does `sublime.find_resources("Spacegray.sublime-theme"); sublime.find_resources("Spacegray Oceanic.sublime-theme");` in the console yield? Doesthe issue go away after an ST restart, i.e. without your `font_face` variable modification?

**Comment by appsforartists** [comment]
```
>>> sublime.find_resources("Spacegray.sublime-theme"); sublime.find_resources("Spacegray Oceanic.sublime-theme");
['Packages/Theme - Spacegray/Spacegray.sublime-theme']
['Packages/Theme - Spacegray/Spacegray Oceanic.sublime-theme', 'Packages/User/Spacegray Oceanic.sublime-theme']
```

**Comment by FichteFoll** [comment]
Ah, I think this is moreso related to the font_size setting rather than font_face, since the Default theme uses 12 pt for that while Spacegray now uses 1.2rem, which seems about accurate in relation to your editor font size (after eyeballing it).

**Comment by appsforartists** [comment]
When I went to the [linked URL](https://www.sublimetext.com/docs/themes.html), I noticed that the documentation says `font.face` and this is using `font_face`.  Is that deviation intentional?  I can foresee it being a source of confusion.

**Comment by erlandh** [comment]
Just adding (clarifying) that the 2.0.0 update produced an unexpected (and unwanted) change in the font size of the user interface. With the global font size now set to 1.2rem in the theme file, the font size of eg. tab labels appears to be 1.2x whatever I have set for the editor font size in my user preferences. I think this is the opposite of the general design principles applied to ST – or at least the core themes, where user interface labels are generally _smaller_ than the editor font size. See comparison screenshot. I've added `"font_size": "0.85rem",` to my theme customisation file now, but just putting this here to question whether it should be the default.

![spacegray-2-font-size](https://github.com/user-attachments/assets/72a07720-d40e-4f37-87f3-06547dc10856)

**Comment by deathaxe** [comment]
>  I noticed that the documentation says font.face and this is using font_face.

`font.face` is the theme rule attribute.

`font_face` is a variable defined by Spacegray theme in `variables` section, to enable global font customization of all UI elemets.

**Comment by deathaxe** [comment]
> With the global font size now set to 1.2rem in the theme file, the font size of eg. tab labels appears to be 1.2x whatever

Relative font size support had been added to ST to exactly enable "auto-adjusting" UI font sizes according to user preferences.

It however seems ST treats theme font sizes and editor font sizes different on each platform.

Latest theme changes were developed on Windows on which UI fonts always appear too small compared to the editor when setting both to same size (e.g. 12pt).

This seems not the case on MacOS at least.
