### ISSUE TITLE
Color scheme changes from 2.0.0 update

### ISSUE THREAD

**Issue by tsutsu** [SublimeText/Spacegray#226]
Same code, when viewed in `base16-ocean.light.tmTheme` from <=1.4.0,

<img width="1786" alt="Screenshot 2024-09-16 at 2 48 11 PM" src="https://github.com/user-attachments/assets/feeb1ef8-420e-4d2e-9955-6b27893ecbe5">

vs. when viewed `Base16 Ocean Light.sublime-color-scheme` from >=2.0.0:

<img width="1786" alt="Screenshot 2024-09-16 at 2 48 22 PM" src="https://github.com/user-attachments/assets/dfd47d9c-0f17-4f50-a418-4b546797f901">

Completely different colors being applied here; the 2.0.0 version is basically an entirely distinct color scheme that just happens to have the same name.

**Comment by deathaxe** [comment]
Ocean Light colors have been slightly tweaked to increase contrast to fix https://github.com/SublimeText/Spacegray/issues/127.

Variable colors have been changed to fix https://github.com/SublimeText/Spacegray/issues/181.

New rules are added for `punctuation` scopes which have been added to all syntaxes during ST3 & 4 dev cycles.

base16 color palette is fully maintained, still.
