### ISSUE TITLE
"font_size" variable seems to have no effect

### ISSUE THREAD

**Issue by minton** [SublimeText/Spacegray#227]
macOS: 14.6.1
ST: 4180

I'm trying to restore the theme after the 2.0 update. I reviewed #225 and found how to adjust the `font_face`. However, the `font_size` doesn't appear to have any effect. I even tried setting it to something giant like `18pt` and it makes no difference. I've tried restarting ST, but it seems to ignore this setting.

My goal is to modify the font size of items in the Side Bar.

Here is my theme customization file:
<img width="1066" alt="settings" src="https://github.com/user-attachments/assets/2d39ed3f-cd61-4c5a-bf08-4e65eb07a815">

Thanks for this awesome theme and for any help you can provide. 🙏

**Comment by deathaxe** [comment]
Only relative font sizes `"1.2rem"` are strings. Absolute font sizes must be integers.
