### ISSUE TITLE
Sidebar theme not changing in ST3 b3061

### ISSUE THREAD

**Issue by subblue** [SublimeText/Spacegray#80]
I'm finding that although I can change the theme of the main edit area between the different styles the sidebar theme is stuck on the ocean dark blue even if I select the eighties or oceans light schemes and then restart ST.

Oddly, every time I change the color scheme the "theme" entry from my user prefs gets removed automatically.

This is with ST3 build 3061 on OSX

**Comment by mamartins** [comment]
same problem here, can't find a solution

**Comment by marcofugaro** [comment]
Thank you @nmn that fixed it for me, after one year and hals this issue persists, and I just freshly installed package control and then those other plugins on windows, so this is a package control issue or ST3?

**Comment by nmn** [comment]
I believe this is a bug in st3.
