### ISSUE TITLE
Theme prevents auto-focusing of file rename window.

### ISSUE THREAD

**Issue by prurph** [SublimeText/Spacegray#86]
It seems the Spacegray theme is preventing the default auto-focusing behavior when you right-click a file > "Rename". With the theme disabled the cursor automatically moves to the "New Name" form that pops up above the status bar at the bottom of the screen, but with Spacegray on this form does not take focus and you have to manually click on it to rename the file.

Not a huge deal but certainly a bit annoying, especially since there's no keyboard shortcut I've been able to find to move the cursor down there after the fact.

**Comment by deathaxe** [comment]
Can't reproduce. Spacegray is just a theme/color scheme without any plugin functionality. It would most likely had been a ST theming engine bug.
