### ISSUE TITLE
How to change font size in theme?

### ISSUE THREAD

**Issue by fbrundu** [SublimeText/Spacegray#88]
Hi,
I am trying to change font size of interface text. I was searching for the `.sublime-theme` file for spacegray (I read this https://www.sublimetext.com/forum/viewtopic.php?f=2&t=7411 ) but I am unable to find it on my file system, I found only a `base16-ocean.dark.tmTheme.cache` file..
How can I achieve that? Is it possible to do?

Thanks

**Comment by deathaxe** [comment]
Works fine in ST4.

Note `ui_scale` can be used to scale whole user interface.
