### ISSUE TITLE
Separators Between Tabs

### ISSUE THREAD

**Issue by noelforte** [SublimeText/Spacegray#96]
In sublime text 3, the feature is added for multiple tabs to be scrolled across. With a large number of tabs open, collapsed tabs that are behind the visible tabs can't be seen, and there's no indicator showing that they are there. As such it's a bit annoying to determine if you have a tab open or not when scrolling through to find it. It would be helpful to be able to see my collapsed tabs.

How sublime text handles it by default:

![screen shot 2014-03-02 at 7 59 15 pm](https://f.cloud.github.com/assets/2560683/2305834/4892ff92-a26f-11e3-84e8-5fcd9a5f944a.png)

How Spacegray handles tabs:

![screen_shot_2014-03-02_at_8_03_08_pm-8](https://f.cloud.github.com/assets/2560683/2305866/7e8095c8-a270-11e3-974e-9c09cd87bacd.png)

**Comment by zenwalker** [comment]
+1

**Comment by deathaxe** [comment]
This is a ST core bug.

see: https://github.com/sublimehq/sublime_text/issues/3776
